/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.ui.FlatPopupMenuBorder;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import static java.util.OptionalDouble.empty;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author lequy
 */
public class MeNuUi extends javax.swing.JFrame {

    javax.swing.border.Border empty = BorderFactory.createEmptyBorder();
    public static MeNuUi b;

    /**
     * Creates new form MeNuUi
     */
    public MeNuUi() {
        initComponents();
        setLocationRelativeTo(null);
        getTime();
        b = this;
        
    }

    public static String TenTK, IDCV;

    public void getTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                SimpleDateFormat D = new SimpleDateFormat("dd/MM/yyyy");
                lblngay.setText(s.format(d) + "-" + D.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnkhachhang = new javax.swing.JButton();
        btntrangchu = new javax.swing.JButton();
        btnmay = new javax.swing.JButton();
        btngiochoi = new javax.swing.JButton();
        btndangxuat = new javax.swing.JButton();
        btndichjvu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbltaikhoan = new javax.swing.JLabel();
        lblngay = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnngiamgia = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnhanvien = new javax.swing.JMenu();
        mqlnhanvien = new javax.swing.JMenuItem();
        mthongke = new javax.swing.JMenu();
        menudichvu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnu_TKKhachHang = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mhoadon = new javax.swing.JMenu();
        mxemhoadon = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        btnkhachhang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnkhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_user_30px_1.png"))); // NOI18N
        btnkhachhang.setText("KHÁCH HÀNG");
        btnkhachhang.setBorder(null);
        btnkhachhang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnkhachhang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnkhachhangMouseMoved(evt);
            }
        });
        btnkhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhachhangActionPerformed(evt);
            }
        });

        btntrangchu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btntrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_home_30px_1.png"))); // NOI18N
        btntrangchu.setText("TRANG CHỦ");
        btntrangchu.setBorder(null);
        btntrangchu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btntrangchu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btntrangchuMouseMoved(evt);
            }
        });
        btntrangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrangchuActionPerformed(evt);
            }
        });

        btnmay.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnmay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Old_Computer_30px.png"))); // NOI18N
        btnmay.setText("MÁY");
        btnmay.setBorder(null);
        btnmay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmay.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnmayMouseMoved(evt);
            }
        });
        btnmay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmayActionPerformed(evt);
            }
        });

        btngiochoi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btngiochoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_timetable_30px.png"))); // NOI18N
        btngiochoi.setText("GIỜ CHƠI");
        btngiochoi.setBorder(null);
        btngiochoi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btngiochoi.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btngiochoiMouseMoved(evt);
            }
        });
        btngiochoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiochoiActionPerformed(evt);
            }
        });

        btndangxuat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btndangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_logout_30px_2.png"))); // NOI18N
        btndangxuat.setText("ĐĂNG XUẤT");
        btndangxuat.setBorder(null);
        btndangxuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndangxuat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btndangxuatMouseMoved(evt);
            }
        });
        btndangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangxuatActionPerformed(evt);
            }
        });

        btndichjvu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btndichjvu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_services_30px.png"))); // NOI18N
        btndichjvu.setText("DỊCH VỤ");
        btndichjvu.setBorder(null);
        btndichjvu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndichjvu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btndichjvuMouseMoved(evt);
            }
        });
        btndichjvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndichjvuActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbltaikhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltaikhoan.setForeground(new java.awt.Color(51, 51, 255));
        lbltaikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_user_30px.png"))); // NOI18N

        lblngay.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblngay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_clock_30px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Old_Computer_30px.png"))); // NOI18N
        jLabel2.setText("NO RICH GAMING");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblngay, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltaikhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lblngay)
                .addGap(18, 18, 18)
                .addComponent(jLabel2))
        );

        btnngiamgia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnngiamgia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_discount_30px_1.png"))); // NOI18N
        btnngiamgia.setText("GIẢM GIÁ");
        btnngiamgia.setBorder(null);
        btnngiamgia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnngiamgia.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnngiamgiaMouseMoved(evt);
            }
        });
        btnngiamgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnngiamgiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnngiamgia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndichjvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btngiochoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btntrangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btngiochoi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btndichjvu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnmay, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnngiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btndangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tab.setBackground(new java.awt.Color(255, 255, 255));
        tab.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_close_20px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tab)))
                .addGap(9, 9, 9))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(419, 50));

        mnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_user_menu_male_30px_1.png"))); // NOI18N
        mnhanvien.setText("Nhân viên");
        mnhanvien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnhanvienMouseClicked(evt);
            }
        });
        mnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnhanvienActionPerformed(evt);
            }
        });

        mqlnhanvien.setText("Quản lý nhân viên");
        mqlnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mqlnhanvienActionPerformed(evt);
            }
        });
        mnhanvien.add(mqlnhanvien);

        jMenuBar1.add(mnhanvien);

        mthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_analytics_30px.png"))); // NOI18N
        mthongke.setText("Thống kê");
        mthongke.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menudichvu.setText("Dịch vụ");
        menudichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menudichvuActionPerformed(evt);
            }
        });
        mthongke.add(menudichvu);

        jMenuItem2.setText("Doanh thu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mthongke.add(jMenuItem2);

        mnu_TKKhachHang.setText("Khách hàng");
        mnu_TKKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_TKKhachHangActionPerformed(evt);
            }
        });
        mthongke.add(mnu_TKKhachHang);

        jMenuItem1.setText("Giờ chơi");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mthongke.add(jMenuItem1);

        jMenuBar1.add(mthongke);

        mhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_paid_bill_30px.png"))); // NOI18N
        mhoadon.setText("Hóa đơn");
        mhoadon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mxemhoadon.setText("Xem hóa đơn");
        mxemhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mxemhoadonActionPerformed(evt);
            }
        });
        mhoadon.add(mxemhoadon);

        jMenuBar1.add(mhoadon);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_info_30px.png"))); // NOI18N
        jMenu4.setText("Thông tin");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngiochoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiochoiActionPerformed
        try {
            tab.setSelectedComponent(pnl_GioChoi_Moi.form_gioChoi);
        } catch (Exception e) {
            pnl_GioChoi_Moi i = new pnl_GioChoi_Moi();
            tab.add("Thuê máy", i);
            tab.setSelectedComponent(i);
        }
    }//GEN-LAST:event_btngiochoiActionPerformed

    private void btndichjvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndichjvuActionPerformed
        try {
            tab.setSelectedComponent(pnl_DichVu1.formDichVu);
        } catch (Exception e) {
            pnl_DichVu1 i = new pnl_DichVu1();
            tab.add("Quản lý dịch vụ", i);
            tab.setSelectedComponent(i);
        }
    }//GEN-LAST:event_btndichjvuActionPerformed

    private void btnmayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmayActionPerformed
        try {
            tab.setSelectedComponent(pnl_May.form_may);
        } catch (Exception e) {
            pnl_May i = new pnl_May();
            tab.add("Quản lý máy", i);
            tab.setSelectedComponent(i);
        }
    }//GEN-LAST:event_btnmayActionPerformed

    private void btntrangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrangchuActionPerformed
 try {
            tab.setSelectedComponent(pnl_GioChoi_Moi.form_gioChoi);
        } catch (Exception e) {
            pnl_GioChoi_Moi i = new pnl_GioChoi_Moi();
            tab.add("Thuê máy", i);
            tab.setSelectedComponent(i);
        }
    }//GEN-LAST:event_btntrangchuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tab.getTabCount() != 0) {
            tab.remove(tab.getSelectedComponent());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menudichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menudichvuActionPerformed
        try {
            tab.setSelectedComponent(pnl_ThongKeUi.form);
        } catch (Exception e) {
            pnl_ThongKeUi i = new pnl_ThongKeUi();
            tab.add("Thống kê", i);
            tab.setSelectedComponent(i);
        }
    }//GEN-LAST:event_menudichvuActionPerformed

    private void btndangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangxuatActionPerformed
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đăng xuất", "Đăng xuất", JOptionPane.OK_CANCEL_OPTION);
        if (chon == 0) {
            new LonginUi().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btndangxuatActionPerformed

    private void btnngiamgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnngiamgiaActionPerformed
        try {
            tab.setSelectedComponent(pnl_GiamGia.formGG);
        } catch (Exception e) {
            pnl_GiamGia i = new pnl_GiamGia();
            tab.add("Quản lý giảm giá", i);
            tab.setSelectedComponent(i);
        }

    }//GEN-LAST:event_btnngiamgiaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            tab.setSelectedComponent(pnl_GioChoi_Moi.form_gioChoi);
        } catch (Exception e) {
            pnl_GioChoi_Moi pnl = new pnl_GioChoi_Moi();
            tab.add("Danh sách máy", pnl);
            tab.setSelectedComponent(pnl);
        }
        if (IDCV.equals("NV")) {
            mthongke.setEnabled(false);
           mnhanvien.setEnabled(false);
           
        }else{
            
        }
        lbltaikhoan.setText(TenTK);
    }//GEN-LAST:event_formWindowOpened

    private void btntrangchuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntrangchuMouseMoved

    }//GEN-LAST:event_btntrangchuMouseMoved

    private void btngiochoiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngiochoiMouseMoved

    }//GEN-LAST:event_btngiochoiMouseMoved

    private void btnkhachhangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkhachhangMouseMoved

    }//GEN-LAST:event_btnkhachhangMouseMoved

    private void btndichjvuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndichjvuMouseMoved

    }//GEN-LAST:event_btndichjvuMouseMoved

    private void btnmayMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmayMouseMoved

    }//GEN-LAST:event_btnmayMouseMoved

    private void btnngiamgiaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnngiamgiaMouseMoved

    }//GEN-LAST:event_btnngiamgiaMouseMoved

    private void btndangxuatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndangxuatMouseMoved


    }//GEN-LAST:event_btndangxuatMouseMoved

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved

    }//GEN-LAST:event_formMouseMoved

    private void btnkhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhachhangActionPerformed
        try {
            tab.setSelectedComponent(pnl_KhachHang.formKH);
        } catch (Exception e) {
            pnl_KhachHang i = new pnl_KhachHang();
            tab.add("Quản lý khách hàng", i);
            tab.setSelectedComponent(i);
        }
    }//GEN-LAST:event_btnkhachhangActionPerformed

    private void mnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnhanvienActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnhanvienActionPerformed

    private void mnu_TKKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_TKKhachHangActionPerformed
        // TODO add your handling code here:
        try {
            tab.setSelectedComponent(pnl_ThongKeKH.formTKKH);
        } catch (Exception e) {
            pnl_ThongKeKH i = new pnl_ThongKeKH();
            tab.add("Thống kê khách hàng", i);
            tab.setSelectedComponent(i);
        }
    }//GEN-LAST:event_mnu_TKKhachHangActionPerformed

    private void mnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnhanvienMouseClicked
       
    }//GEN-LAST:event_mnhanvienMouseClicked

    private void mqlnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mqlnhanvienActionPerformed
        // TODO add your handling code here:
        try {
            tab.setSelectedComponent(pnlNhanVienUI.pnl_nhanVienUI);
        } catch (Exception e) {
            pnlNhanVienUI i = new pnlNhanVienUI();
            tab.add("Quản lý nhân viên", i);
            tab.setSelectedComponent(i);
        }
    }//GEN-LAST:event_mqlnhanvienActionPerformed

    private void mxemhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mxemhoadonActionPerformed
        // TODO add your handling code here:
        try {
            tab.setSelectedComponent(pnl_dsHoadon.form);
        } catch (Exception e) {
            pnl_dsHoadon i = new pnl_dsHoadon();
            tab.add("Danh sách hóa đơn", i);
            tab.setSelectedComponent(i);
        }
        
    }//GEN-LAST:event_mxemhoadonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            tab.setSelectedComponent(pnl_ThongKeGC.formTKGc);
        } catch (Exception e) {
            pnl_ThongKeGC i = new pnl_ThongKeGC();
            tab.add("Thống kê giờ chơi", i);
            tab.setSelectedComponent(i);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try {
            tab.setSelectedComponent(pnl_ThongKeDT.form);
        } catch (Exception e) {
            pnl_ThongKeDT i = new pnl_ThongKeDT();
            tab.add("Thống kê doanh thu", i);
            tab.setSelectedComponent(i);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());

        } catch (Exception e) {
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeNuUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangxuat;
    private javax.swing.JButton btndichjvu;
    private javax.swing.JButton btngiochoi;
    private javax.swing.JButton btnkhachhang;
    private javax.swing.JButton btnmay;
    private javax.swing.JButton btnngiamgia;
    private javax.swing.JButton btntrangchu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblngay;
    private javax.swing.JLabel lbltaikhoan;
    private javax.swing.JMenuItem menudichvu;
    private javax.swing.JMenu mhoadon;
    private javax.swing.JMenu mnhanvien;
    private javax.swing.JMenuItem mnu_TKKhachHang;
    private javax.swing.JMenuItem mqlnhanvien;
    private javax.swing.JMenu mthongke;
    private javax.swing.JMenuItem mxemhoadon;
    public javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
