/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Service.IKhachHangService;
import Service_impl.KhachHang_Service;
import static View.pnl_KhachHang.formKH;
import ViewModel.KhachHang_View;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daoqu
 */
public class pnl_ThongKeKH extends javax.swing.JPanel {

    public static pnl_ThongKeKH formTKKH;
    private IKhachHangService _iHangService;
    List<KhachHang_View> ls;
    
    /**
     * Creates new form NewJPanel
     */
    public pnl_ThongKeKH() {
        initComponents();
        formTKKH = this;
        ls = new ArrayList<>();
        _iHangService = new KhachHang_Service();
       
    }
    public void loadKhachMoi(){
        List<KhachHang_View> ds = this._iHangService.KhachMoi();
        DefaultTableModel dtm = (DefaultTableModel) this.tblkhachhang.getModel();
        dtm.setRowCount(0);
        for (KhachHang_View d : ds) {
            Object[] rowData = {
                d.getStt(),
                d.getMa(),
                d.getHoTen(),
                d.gettrangthai()

            };
            dtm.addRow(rowData);
        }

    }
     public void loadKhachQuen(){
        List<KhachHang_View> ds = this._iHangService.KhachQuen();
        DefaultTableModel dtm = (DefaultTableModel) this.tblkhachhang.getModel();
        dtm.setRowCount(0);
        for (KhachHang_View d : ds) {
            Object[] rowData = {
                d.getStt(),
                d.getMa(),
                d.getHoTen(),
                d.gettrangthai()

            };
            System.out.println("");
            dtm.addRow(rowData);
        }

    }
          public void loadKhachTT(){
        List<KhachHang_View> ds = this._iHangService.KhachTT();
        DefaultTableModel dtm = (DefaultTableModel) this.tblkhachhang.getModel();
        dtm.setRowCount(0);
        for (KhachHang_View d : ds) {
            Object[] rowData = {
                d.getStt(),
                d.getMa(),
                d.getHoTen(),
                d.gettrangthai()

            };
            dtm.addRow(rowData);
        }

    }
        public void loadTable(){
        List<KhachHang_View> ds = this._iHangService.getALllDM();
        DefaultTableModel dtm = (DefaultTableModel) this.tblkhachhang.getModel();
        dtm.setRowCount(0);
        for (KhachHang_View d : ds) {
            Object[] rowData = {
                d.getStt(),
                d.getMa(),
                d.getHoTen(),
                d.gettrangthai()

            };
            dtm.addRow(rowData);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkhachhang = new javax.swing.JTable();
        btnkhachmoi = new javax.swing.JButton();
        btnkhachquen = new javax.swing.JButton();
        btnkhachthanhtoan = new javax.swing.JButton();
        btndanhsach = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("THỐNG KÊ KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MÃ KH", "HỌ TÊN KH", "TRẠNG THÁI"
            }
        ));
        jScrollPane1.setViewportView(tblkhachhang);

        btnkhachmoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnkhachmoi.setText("KHÁCH MỚI");
        btnkhachmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhachmoiActionPerformed(evt);
            }
        });

        btnkhachquen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnkhachquen.setText("KHÁCH QUEN");
        btnkhachquen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhachquenActionPerformed(evt);
            }
        });

        btnkhachthanhtoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnkhachthanhtoan.setText("KHÁCH THANH TOÁN NHIỀU TIỀN NHẤT");
        btnkhachthanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhachthanhtoanActionPerformed(evt);
            }
        });

        btndanhsach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btndanhsach.setText("Danh sách KH");
        btndanhsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndanhsachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndanhsach)
                .addGap(45, 45, 45)
                .addComponent(btnkhachmoi)
                .addGap(44, 44, 44)
                .addComponent(btnkhachquen)
                .addGap(36, 36, 36)
                .addComponent(btnkhachthanhtoan)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkhachmoi)
                    .addComponent(btnkhachquen)
                    .addComponent(btnkhachthanhtoan)
                    .addComponent(btndanhsach))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnkhachmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhachmoiActionPerformed
        // TODO add your handling code here:
        loadKhachMoi();
    }//GEN-LAST:event_btnkhachmoiActionPerformed

    private void btndanhsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndanhsachActionPerformed
        // TODO add your handling code here:
         loadTable();
    }//GEN-LAST:event_btndanhsachActionPerformed

    private void btnkhachquenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhachquenActionPerformed
        // TODO add your handling code here:
        loadKhachQuen();
    }//GEN-LAST:event_btnkhachquenActionPerformed

    private void btnkhachthanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhachthanhtoanActionPerformed
        // TODO add your handling code here:
        loadKhachTT();
    }//GEN-LAST:event_btnkhachthanhtoanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndanhsach;
    private javax.swing.JButton btnkhachmoi;
    private javax.swing.JButton btnkhachquen;
    private javax.swing.JButton btnkhachthanhtoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblkhachhang;
    // End of variables declaration//GEN-END:variables
}
