/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Service.IThueMay_Services;
import Service_impl.ThueMay_Services;
import Ulti.JDBC_Helper;
import ViewModel.ThueMay;
import ViewModel.ThueMay_View;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.*;



/**
 *
 * @author daoqu
 */
public class pnl_ThongKeGC extends javax.swing.JPanel {
 public static pnl_ThongKeGC formTKGc;
    private IThueMay_Services _iGioService;
    List<ThueMay_View> ls;
    List<ThueMay> lsa;
    /**
     * Creates new form pnl_ThongKeGC
     */
    public pnl_ThongKeGC() {
        initComponents();
        _iGioService=new ThueMay_Services();
        ls=new ArrayList<>();
        lsa=new ArrayList<>();
        formTKGc  = this;
        
    }
 public void loadTable(){
        List<ThueMay> ds = this._iGioService.laygio();
        DefaultTableModel dtm = (DefaultTableModel) this.tblkhachhang.getModel();
        dtm.setRowCount(0);
        for (ThueMay d : ds) {
            Object[] rowData = {
                d.getStt(),
                d.getTgBatDau(),
                d.getDem()

            };
            dtm.addRow(rowData);
        }

    }
 public void loadGioMax(){
        List<ThueMay> ds = this._iGioService.laygioMax();
        DefaultTableModel dtm = (DefaultTableModel) this.tblkhachhang.getModel();
        dtm.setRowCount(0);
        for (ThueMay d : ds) {
            Object[] rowData = {
                d.getStt(),
                d.getTgBatDau(),
                d.getDem()

            };
            dtm.addRow(rowData);
        }

    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btngcd = new javax.swing.JButton();
        btnds = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkhachhang = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("THỐNG KÊ GIỜ CHƠI");

        btngcd.setText("Giờ Chơi Đông Khách Nhất");
        btngcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngcdActionPerformed(evt);
            }
        });

        btnds.setText("Danh Sách Giờ Chơi");
        btnds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndsActionPerformed(evt);
            }
        });

        tblkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "GIỜ CHƠI", "SỐ LƯỢNG KH"
            }
        ));
        jScrollPane1.setViewportView(tblkhachhang);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(271, 271, 271))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btnds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                .addComponent(btngcd)
                .addGap(102, 102, 102))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngcd)
                    .addComponent(btnds))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndsActionPerformed
        // TODO add your handling code here:
        loadTable();
    }//GEN-LAST:event_btndsActionPerformed

    private void btngcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngcdActionPerformed
        // TODO add your handling code here:
        loadGioMax();
    }//GEN-LAST:event_btngcdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnds;
    private javax.swing.JButton btngcd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblkhachhang;
    // End of variables declaration//GEN-END:variables
}
